%YAML:1.0
---
input_ports: 8888
output_ports: 9999
output_ips: 127.0.0.1
cam_idx: 0
tif_map: ../demo/data/MASA_4670.tif
png_map: ../demo/data/MASA_4670.png
visualization: false
edge_log_saving: true
aggr_log_saving: true